# Generated by Django 3.2 on 2021-05-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Galle', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0767630514', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='Galle', max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default='0767630514', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
