# Generated by Django 3.2 on 2021-05-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catogories', '0001_initial'),
        ('products', '0008_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catogories.category'),
        ),
    ]
