# Generated by Django 3.2.3 on 2021-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210527_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
